springdoc:
  swagger-ui:
    path: /api.html
  version: v0.0.1
  paths-to-match:
    - /**


spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#    properties:
#      hibernate.format_sql: true  # (3) SQL pretty print

  output:
    ansi:
      enabled: always

#Sl4fj
logging:
  level:
    root: info
    main_project:
      udongs: debug

