spring:
  profiles:
    active: sensitive
  #파일 업로드 사이즈 2MB로 수정
  servlet:
    multipart:
      maxFileSize=2MB
      maxRequestSize=2MB

springdoc:
  use-fqn: true
  swagger-ui:
    path: /api.html
  version: v0.0.1
  paths-to-match:
    - /**

#Sl4fj
logging:
  level:
    root: info
    main_project:
      udongs: debug

